server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/mateoBlencio/funciones-microservicios
  application:
    name: config-service

